### ISSUE TITLE
Boilerplate ERDDAP resource title and description

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/ckan#14]
**Describe the bug**
ERDDAP resources entered and described via the CIOOS metadata intake have some boilerplate titles and descriptions in the CKAN record. Ie, regardless of what you enter for a title or a description in the metadata form, the resource title and description in CKAN is always the same boilerplate title: "ERDDAP Data Subset Form', and description: "ERDDAP's version of the OPeNDAP .html web page for this dataset..."

This happens on the IYS and the Hakai CKAN instances...

**Screenshots**

![image](https://user-images.githubusercontent.com/26495640/133523853-b7dd43dc-0f50-428f-a69e-43422d9d2181.png)

Despite the title and empty description entered above, I always end up with the boilerplate ERDDAP text below:

![Screen Shot 2021-09-15 at 3 43 06 PM](https://user-images.githubusercontent.com/26495640/133523212-336111bf-b10c-46bc-859e-5261c27509d9.png)

**Comment by Br-Johnson** [comment]
This is still an issue

**Comment by fostermh** [comment]
It appears this is not a ckan issue. when I look at the xml files the boilerplate title and description are there so that is what ckan uses. The issue is likely with the metadata form and the conversion to xml.

**Comment by Br-Johnson** [comment]
@n-a-t-e Would it be possible to remove this?

**Comment by fostermh** [comment]
fixed by https://github.com/cioos-siooc/metadata-xml/pull/99

**Comment by Br-Johnson** [comment]
@fostermh This issue still exists in the IYS Catalogue. See https://iys.hakai.org/dataset/ca-cioos_a8fd5ba4-5407-4d03-914f-27eb7f3f8121

The boilerplate ERDDAP name and description are still there despite the metadata intake form having different values seen below:

![image](https://user-images.githubusercontent.com/26495640/158656695-ebff5c51-9ded-4a29-b845-e97f6a006467.png)

Is there another step required to have this fix propagate to the IYS catalogue?

**Comment by fostermh** [comment]
cleared and harvest data. resource name's have been updated. It appears that datasets do not update when resource-related metadata is changed. something I will have to look into.
